package net.sbit.enums;

public enum TipoVentana {
    PANTALLA_PRINCIPAL, NUEVO_USUARIO, LISTA_USUARIOS, ADMINISTRAR_PERMISO_EN_VENTANA, 
    CREAR_PERFIL, ADMINISTRAR_VENTANAS_A_PERFIL, NUEVO_COMPONENTE, LISTAR_COMPONENTES,
    NUEVA_VENTANA,ASIGNAR_COMPONENTE_A_VENTANA
}
