package net.sbit.model;// default package

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Perfil generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "perfil", catalog = "generalDB")
public class Perfil implements java.io.Serializable {

    private String nombrePerfil;
    private Boolean estadoPerfil;

    public Perfil() {
    }

    public Perfil(String nombrePerfil) {
	this.nombrePerfil = nombrePerfil;
    }

    public Perfil(String nombrePerfil, Boolean estadoPerfil) {
	this.nombrePerfil = nombrePerfil;
	this.estadoPerfil = estadoPerfil;
    }

    @Id

    @Column(name = "nombre_perfil", unique = true, nullable = false, length = 40)
    public String getNombrePerfil() {
	return this.nombrePerfil;
    }

    public void setNombrePerfil(String nombrePerfil) {
	this.nombrePerfil = nombrePerfil;
    }

    @Column(name = "estado_perfil")
    public Boolean getEstadoPerfil() {
	return this.estadoPerfil;
    }

    public void setEstadoPerfil(Boolean estadoPerfil) {
	this.estadoPerfil = estadoPerfil;
    }

}
