package net.sbit.model;// default package

// Generated 20/12/2015 17:00:03 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PerfilVentanaComponente generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "perfil_ventana_componente", catalog = "generalDB")
public class PerfilVentanaComponente implements java.io.Serializable {

    private PerfilVentanaComponenteId id;
    private Boolean estado;

    public PerfilVentanaComponente() {
    }

    public PerfilVentanaComponente(PerfilVentanaComponenteId id) {
	this.id = id;
    }

    public PerfilVentanaComponente(PerfilVentanaComponenteId id, Boolean estado) {
	this.id = id;
	this.estado = estado;
    }

    @EmbeddedId

    @AttributeOverrides({
	    @AttributeOverride(name = "nomPerVpc", column = @Column(name = "nom_per_vpc", nullable = false, length = 40)),
	    @AttributeOverride(name = "nomComVpc", column = @Column(name = "nom_com_vpc", nullable = false, length = 40)),
	    @AttributeOverride(name = "nomVenVpc", column = @Column(name = "nom_ven_vpc", nullable = false, length = 40)) })
    public PerfilVentanaComponenteId getId() {
	return this.id;
    }

    public void setId(PerfilVentanaComponenteId id) {
	this.id = id;
    }

    @Column(name = "estado")
    public Boolean getEstado() {
	return this.estado;
    }

    public void setEstado(Boolean estado) {
	this.estado = estado;
    }

}
