package net.sbit.model;// default package

// Generated 20/12/2015 17:00:03 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PerfilVentanaComponenteId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class PerfilVentanaComponenteId implements java.io.Serializable {

    private String nomPerVpc;
    private String nomComVpc;
    private String nomVenVpc;

    public PerfilVentanaComponenteId() {
    }

    public PerfilVentanaComponenteId(String nomPerVpc, String nomComVpc, String nomVenVpc) {
	this.nomPerVpc = nomPerVpc;
	this.nomComVpc = nomComVpc;
	this.nomVenVpc = nomVenVpc;
    }

    @Column(name = "nom_per_vpc", nullable = false, length = 40)
    public String getNomPerVpc() {
	return this.nomPerVpc;
    }

    public void setNomPerVpc(String nomPerVpc) {
	this.nomPerVpc = nomPerVpc;
    }

    @Column(name = "nom_com_vpc", nullable = false, length = 40)
    public String getNomComVpc() {
	return this.nomComVpc;
    }

    public void setNomComVpc(String nomComVpc) {
	this.nomComVpc = nomComVpc;
    }

    @Column(name = "nom_ven_vpc", nullable = false, length = 40)
    public String getNomVenVpc() {
	return this.nomVenVpc;
    }

    public void setNomVenVpc(String nomVenVpc) {
	this.nomVenVpc = nomVenVpc;
    }

    public boolean equals(Object other) {
	if ((this == other))
	    return true;
	if ((other == null))
	    return false;
	if (!(other instanceof PerfilVentanaComponenteId))
	    return false;
	PerfilVentanaComponenteId castOther = (PerfilVentanaComponenteId) other;

	return ((this.getNomPerVpc() == castOther.getNomPerVpc()) || (this.getNomPerVpc() != null
		&& castOther.getNomPerVpc() != null && this.getNomPerVpc().equals(castOther.getNomPerVpc())))
		&& ((this.getNomComVpc() == castOther.getNomComVpc()) || (this.getNomComVpc() != null
			&& castOther.getNomComVpc() != null && this.getNomComVpc().equals(castOther.getNomComVpc())))
		&& ((this.getNomVenVpc() == castOther.getNomVenVpc()) || (this.getNomVenVpc() != null
			&& castOther.getNomVenVpc() != null && this.getNomVenVpc().equals(castOther.getNomVenVpc())));
    }

    public int hashCode() {
	int result = 17;

	result = 37 * result + (getNomPerVpc() == null ? 0 : this.getNomPerVpc().hashCode());
	result = 37 * result + (getNomComVpc() == null ? 0 : this.getNomComVpc().hashCode());
	result = 37 * result + (getNomVenVpc() == null ? 0 : this.getNomVenVpc().hashCode());
	return result;
    }

}
