package net.sbit.model;// default package// default package

// Generated 20/12/2015 17:00:03 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ventana generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "ventana", catalog = "generalDB")
public class Ventana implements java.io.Serializable {

    private String nombreVentana;

    public Ventana() {
    }

    public Ventana(String nombreVentana) {
	this.nombreVentana = nombreVentana;
    }

    @Id

    @Column(name = "nombre_ventana", unique = true, nullable = false, length = 40)
    public String getNombreVentana() {
	return this.nombreVentana;
    }

    public void setNombreVentana(String nombreVentana) {
	this.nombreVentana = nombreVentana;
    }

}
