package net.sbit.model;// default package// default package

// Generated 20/12/2015 17:00:03 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VentanaComponente generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "ventana_componente", catalog = "generalDB")
public class VentanaComponente implements java.io.Serializable {

    private VentanaComponenteId id;

    public VentanaComponente() {
    }

    public VentanaComponente(VentanaComponenteId id) {
	this.id = id;
    }

    @EmbeddedId

    @AttributeOverrides({
	    @AttributeOverride(name = "nomComponente", column = @Column(name = "nom_componente", nullable = false, length = 40)),
	    @AttributeOverride(name = "nomVentana", column = @Column(name = "nom_ventana", nullable = false, length = 40)) })
    public VentanaComponenteId getId() {
	return this.id;
    }

    public void setId(VentanaComponenteId id) {
	this.id = id;
    }

}
